export const ACTIONS = {
  GET_MOVIES: "GET_MOVIES",
  CLEAN_SEATS_ARRAY: "CLEAN_SEATS_ARRAY",
  GET_SINGLE_MOVIE: "GET_SINGLE_MOVIE",
  REMOVE_SEAT: "REMOVE_SEAT",
  SET_BOOK_STATUS: "SET_BOOK_STATUS",
  SET_SEATS: "SET_SEATS"
};
